#!/bin/bash

unset SNAP
unset SNAP_COMMON
unset SNAP_DATA
unset SNAP_USER_COMMON
unset SNAP_USER_DATA
unset SNAP_INSTANCE_NAME
unset SNAP_INSTANCE_KEY
unset SNAP_LIBRARY_PATH

[ -n "$GTK_PATH_VSCODE_SNAP_ORIG" ] && export GTK_PATH="$GTK_PATH_VSCODE_SNAP_ORIG" || unset GTK_PATH
[ -n "$GIO_MODULE_DIR_VSCODE_SNAP_ORIG" ] && export GIO_MODULE_DIR="$GIO_MODULE_DIR_VSCODE_SNAP_ORIG" || unset GIO_MODULE_DIR
[ -n "$GTK_IM_MODULE_FILE_VSCODE_SNAP_ORIG" ] && export GTK_IM_MODULE_FILE="$GTK_IM_MODULE_FILE_VSCODE_SNAP_ORIG" || unset GTK_IM_MODULE_FILE
[ -n "$GSETTINGS_SCHEMA_DIR_VSCODE_SNAP_ORIG" ] && export GSETTINGS_SCHEMA_DIR="$GSETTINGS_SCHEMA_DIR_VSCODE_SNAP_ORIG" || unset GSETTINGS_SCHEMA_DIR
[ -n "$XDG_DATA_DIRS_VSCODE_SNAP_ORIG" ] && export XDG_DATA_DIRS="$XDG_DATA_DIRS_VSCODE_SNAP_ORIG"
[ -n "$XDG_DATA_HOME_VSCODE_SNAP_ORIG" ] && export XDG_DATA_HOME="$XDG_DATA_HOME_VSCODE_SNAP_ORIG"
[ -n "$GTK_EXE_PREFIX_VSCODE_SNAP_ORIG" ] && export GTK_EXE_PREFIX="$GTK_EXE_PREFIX_VSCODE_SNAP_ORIG" || unset GTK_EXE_PREFIX
[ -n "$LOCPATH_VSCODE_SNAP_ORIG" ] && export LOCPATH="$LOCPATH_VSCODE_SNAP_ORIG" || unset LOCPATH

cd "$(dirname "$0")/build"
./Messenger
